name = "ITensorSiteKit"
uuid = "ffe6b83a-dc94-4fa6-83e9-b4b377faf66b"
version = "0.1.0"
authors = ["sota shimozono <shimozono-sota631@g.ecc.u-tokyo.ac.jp>"]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
